Feature/#140202783/static page management
andela/jiayou-rc pull request #12
Opened 2017-03-21 01:52 UTC by andela-oawofadeju

#### What does this PR do?
This PR adds static page feature to the reaction app

#### Description of Task to be completed?
Create and edit static pages, such as Contact, About, or Support.

#### How should this be manually tested?
An Admin can create, edit or delete any static page

2017-03-21 09:42 UTC, rowlandekemezie requested changes
Take note of the comments and respond accordingly

2017-03-21 09:42 UTC, rowlandekemezie commented on imports/plugins/included/staticPagesStart/client/templates/staticPageStart.js
> +Template.staticPages.onDestroyed(()=>{
We should have space in-between `=>`

2017-03-21 09:42 UTC, rowlandekemezie commented on imports/plugins/included/staticPagesStart/client/templates/staticPageStart.js
> +  "click .static-pages-new": ()=> {
Space in-between `=>`

2017-03-21 09:42 UTC, rowlandekemezie commented on imports/plugins/included/staticPagesStart/client/templates/staticPageStart.js
> +  "click .static-pages-update": ()=> {
Space in-between `=>`

2017-03-21 09:42 UTC, rowlandekemezie commented on imports/plugins/included/staticPagesStart/client/templates/staticPageStart.js
> +    Meteor.call("updatePage", _id, title, slug, content, shopId,  function (err) {
Can we not be consistent with the use of arrow function here?

2017-03-21 09:42 UTC, rowlandekemezie commented on imports/plugins/included/staticPagesStart/client/templates/staticPageStart.js
> +  "click #static-pages-menu-toggle": (event)=> {
Space in-between `=>`

2017-03-21 09:42 UTC, rowlandekemezie commented on imports/plugins/included/staticPagesStart/client/templates/staticPageStart.js
> +  "click .editPage": (event)=> {
Space in-between `=>`

2017-03-21 09:42 UTC, rowlandekemezie commented on imports/plugins/included/staticPagesStart/client/templates/staticPageStart.js
> +  "click .deletePage": (event)=> {
Space in-between `=>`

2017-03-21 09:42 UTC, rowlandekemezie commented on server/methods/core/staticPage.js
> +import {StaticPages } from "/lib/collections";
Space needed here `{ StaticPages }`

2017-03-21 09:42 UTC, rowlandekemezie commented on imports/plugins/included/staticPagesStart/client/templates/staticPageStart.js
> +  "click .addPage": ()=> {
Space in-between `=>`

2017-03-21 09:42 UTC, mentrie commented on imports/plugins/included/staticPagesStart/client/templates/staticPageStart.html
> +              <input style="display:none" type="text" class="form-control" id="static-page-id">
Can we avoid using inline styling.

2017-03-21 09:42 UTC, mentrie commented on client/modules/accounts/templates/dropdown/dropdown.html
> +        <i class=""></i>
Are we using this for anything?

2017-03-21 09:42 UTC, mentrie commented on imports/plugins/included/default-theme/client/styles/staticPages/staticPages.less
> +#sidebar-wrapper {
**Nitpick**
I would recommend not using too many negative margins in your application. Flexbox model can come in handy for you

2017-03-21 09:42 UTC, mentrie commented on imports/plugins/included/staticPagesStart/client/templates/staticPageStart.js
> +Template.staticPages.onDestroyed(()=>{
If arrow function works here, I doubt it won't work in other templates

2017-03-21 09:42 UTC, mentrie commented on imports/plugins/included/staticPagesStart/server/policy.js
> +BrowserPolicy.content.allowOriginForAll("*.facebook.com");
Any reason why we're using these policies? I think we already have these dependencies in our project.

2017-03-21 15:20 UTC, andela-oawofadeju commented on client/modules/accounts/templates/dropdown/dropdown.html
> +        <i class=""></i>
Yes, this list the number of pages in the dropdown menu on the navigation bar. It increases as more pages are being created.

2017-03-22 11:04 UTC, rowlandekemezie approved these changes
LGTM

2017-03-28 09:39 UTC, merged