Chore/#140474061/integrate all badges and coverall to project repository
andela/jiayou-rc pull request #5
Opened 2017-03-10 19:37 UTC by andela-oawofadeju

#### What does this PR do?

This PR is meant to update the badges with the project repository and attach coveralls.

#### Description of Task to be completed:
We want contributors to see updated steps for contributing to our application and the badges pointed to our repositories on CI, etc.

2017-03-15 15:33 UTC, rowlandekemezie requested changes

2017-03-15 15:33 UTC, mentrie commented on README.md
> +[![Coverage Status](https://coveralls.io/repos/github/andela/jiayou-rc/badge.svg?branch=develop)](https://coveralls.io/github/andela/jiayou-rc?branch=develop)
We can allow coverage status on all branches. I don't think we need `branch=develop` appended to the status report

2017-03-15 15:33 UTC, mentrie commented on package.json
> +    "google-libphonenumber": "^2.0.11",
What's this dependency for?

2017-03-15 15:33 UTC, mentrie commented on README.md
> +[![bitHound Overall Score](https://www.bithound.io/github/andela/jiayou-rc/badges/score.svg)](https://www.bithound.io/github/andela/jiayou-rc) [![bitHound Dev Dependencies](https://www.bithound.io/gi
Circle CI report status doesn't show on the branch. please, it's important for us to have all the branches showing their status based on the last build. Why are you pointing `bithound.io` to develop branch

2017-03-15 15:33 UTC, mentrie commented on .meteor/versions
> +practicalmeteor:loglevel@1.2.0_2
Curious if we need all these dependencies or they were meant for testing purposes and you forgot to clean them up

2017-03-15 15:38 UTC, andela-oawofadeju commented on package.json
> +    "google-libphonenumber": "^2.0.11",
I didn't add that intentionally. It must have been a mistake while working with the multivendor task

2017-03-15 15:38 UTC, andela-oawofadeju commented on README.md
> +[![Coverage Status](https://coveralls.io/repos/github/andela/jiayou-rc/badge.svg?branch=develop)](https://coveralls.io/github/andela/jiayou-rc?branch=develop)
Oh okay

2017-03-15 15:40 UTC, andela-oawofadeju commented on README.md
> +[![bitHound Overall Score](https://www.bithound.io/github/andela/jiayou-rc/badges/score.svg)](https://www.bithound.io/github/andela/jiayou-rc) [![bitHound Dev Dependencies](https://www.bithound.io/gi
Okay, I will fix them now

2017-03-19 22:05 UTC, rowlandekemezie approved these changes
LGTM

2017-03-27 10:48 UTC, merged